version: '3'
services:
  spark-master:
    build: ./master
    platform: linux/arm64/v8
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      
  spark-worker-1:
    build: ./worker
    platform: linux/arm64/v8
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "7071:7071"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      
  spark-worker-2:
    build: ./worker
    platform: linux/arm64/v8
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
      - "7072:7072"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      
  spark-worker-3:
    build: ./worker
    platform: linux/arm64/v8
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
      - "7073:7073"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      
